#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KinskyDroid.Resource", IsApplication=true)]

namespace KinskyDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Album = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AlbumArtError = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Array = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Artist = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BackButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backbuttonfocused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backbuttonnormal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backbuttonpressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Bookmark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BottomFiller = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int BottomLeftEdge = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int BottomRightEdge = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int BrowserDown = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ButtonBackground = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int buttonfocused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int buttonnormal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int buttonpressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int CD = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ClockIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ClockIconElapsed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ClockIconRemaining = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Delete = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int DeleteDown = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Directory = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int DisclosureIndicator = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int EditModeButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Error = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int FfwdButton = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Folder = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int FrwdButton = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int GradientBackground = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Home = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int HomeDown = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int HomeOn = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int HourGlass = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int HourGlass2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Icon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int LeftFiller = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Library = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int LinnLogo = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int List = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Loading = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int MoveDown = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int MoveDownButton = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int MoveDownDisabled = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int MoveUp = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int MoveUpButton = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int MoveUpDisabled = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Multi = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int MultiDown = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int MultiOn = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int MultiOnDown = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Mute = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int MuteActive = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int MuteIcon = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Pause = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int PauseButton = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int PauseDown = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int PauseOver = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Play = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int PlayButton = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int PlayDown = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Playing = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Playlist = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int PlaylistItem = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int PlaylistSource = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int PlayOver = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Radio = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int RefreshButton = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Repeat = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int RepeatButton = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int RepeatButtonForeground = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int RepeatDown = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int RepeatOn = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int RepeatOnDown = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int RequestDelete = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int RequestDeleteButton = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int RequestDeleteConfirm = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int RightFiller = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int Rocker = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int RockerLeftDown = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int RockerRightDown = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int Room = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int RoomSource = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int Save = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int SaveDown = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int Screws = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ScrewsLarge = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int Sender = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int SenderNoSend = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int Settings = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int Shuffle = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ShuffleButton = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ShuffleButtonForeground = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ShuffleDown = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ShuffleOn = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ShuffleOnDown = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int SkipBack = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int SkipBackButton = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int SkipBackDown = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int SkipBackOver = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int SkipForward = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int SkipForwardButton = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int SkipForwardDown = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int SkipForwardOver = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int Source = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int Standby = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int StandbyButton = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int StandbyButtonForeground = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int StandbyDown = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int StandbyOn = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int StandbyOnDown = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int Stop = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int StopButton = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int StopDown = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int StopOver = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int Tick = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int TopBarFiller = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int TopFiller = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int TopLeftEdge = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int TopRightEdge = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int Track = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int TramLines = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int UPNP = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int Video = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int VolumeDown = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int VolumeUp = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int Wheel = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int WheelBackground = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int WheelGrip = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int WheelLarge = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int WheelLargeOver = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int WheelMute = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int WheelOver = 2130837637;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int backbutton = 2131034116;
			
			// aapt resource value: 0x7f05002c
			public const int bottombar = 2131034156;
			
			// aapt resource value: 0x7f050018
			public const int browser = 2131034136;
			
			// aapt resource value: 0x7f050000
			public const int browserbuttons = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int browserbuttonscontainer = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int browsercontrols = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int browsercontrolscontainer = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int browsereditmodebutton = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int browsererrorhomebutton = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int browsererroricon = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int browsererrorretrybutton = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int browsererrortext = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int browseritemfirstline = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int browseritemicon = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int browseritemiconcontainer = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int browseritemnavigationicon = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int browseritemsecondline = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int browseritemtechnicalinfo = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int browseritemthirdline = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int browsermenuplaylater = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int browsermenuplaynext = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int browsermenuplaynow = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int browsermenutitle = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int browserthrobber = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int buttoncontrolbutton1 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int buttoncontrolbutton2 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int buttoncontrolbutton3 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int confirmdeletebutton = 2131034141;
			
			// aapt resource value: 0x7f05005d
			public const int currentroom = 2131034205;
			
			// aapt resource value: 0x7f050066
			public const int currentsource = 2131034214;
			
			// aapt resource value: 0x7f050027
			public const int fullscreenartworkcontainerphone = 2131034151;
			
			// aapt resource value: 0x7f050033
			public const int helpaboutcompany = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int helpaboutcopyright = 2131034162;
			
			// aapt resource value: 0x7f050034
			public const int helpaboutdescription = 2131034164;
			
			// aapt resource value: 0x7f05002f
			public const int helpabouticon = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int helpaboutproduct = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int helpaboutversion = 2131034161;
			
			// aapt resource value: 0x7f050036
			public const int hiddencontainerphone = 2131034166;
			
			// aapt resource value: 0x7f050005
			public const int locationdisplay = 2131034117;
			
			// aapt resource value: 0x7f050029
			public const int mainlayout = 2131034153;
			
			// aapt resource value: 0x7f05002d
			public const int middlesection = 2131034157;
			
			// aapt resource value: 0x7f050037
			public const int movedownbutton = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int moveupbutton = 2131034168;
			
			// aapt resource value: 0x7f050026
			public const int playlist = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int playlistbuttons = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int playlistcontainerphone = 2131034148;
			
			// aapt resource value: 0x7f05003c
			public const int playlistdeletebutton = 2131034172;
			
			// aapt resource value: 0x7f050039
			public const int playlisteditbuttons = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int playlisteditmodebutton = 2131034170;
			
			// aapt resource value: 0x7f050045
			public const int playlistitemfirstline = 2131034181;
			
			// aapt resource value: 0x7f050040
			public const int playlistitemicon = 2131034176;
			
			// aapt resource value: 0x7f05003f
			public const int playlistitemiconcontainer = 2131034175;
			
			// aapt resource value: 0x7f050044
			public const int playlistitemjumptoroom = 2131034180;
			
			// aapt resource value: 0x7f050042
			public const int playlistitemplaying = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int playlistitemplayingcontainer = 2131034177;
			
			// aapt resource value: 0x7f050046
			public const int playlistitemsecondline = 2131034182;
			
			// aapt resource value: 0x7f050043
			public const int playlistitemtechnicalinfo = 2131034179;
			
			// aapt resource value: 0x7f050047
			public const int playlistitemthirdline = 2131034183;
			
			// aapt resource value: 0x7f05003b
			public const int playlistsavebutton = 2131034171;
			
			// aapt resource value: 0x7f050022
			public const int playlisttopsectionphone = 2131034146;
			
			// aapt resource value: 0x7f050002
			public const int playnownextlaterbutton = 2131034114;
			
			// aapt resource value: 0x7f05003e
			public const int repeatbutton = 2131034174;
			
			// aapt resource value: 0x7f050048
			public const int requestdeletebutton = 2131034184;
			
			// aapt resource value: 0x7f05004c
			public const int roomandsourceviewswitcher = 2131034188;
			
			// aapt resource value: 0x7f050054
			public const int roomlist = 2131034196;
			
			// aapt resource value: 0x7f05004d
			public const int roomlistcontainer = 2131034189;
			
			// aapt resource value: 0x7f05005b
			public const int roomlistheader = 2131034203;
			
			// aapt resource value: 0x7f050050
			public const int roomlisttitle = 2131034192;
			
			// aapt resource value: 0x7f05004e
			public const int roomlisttitlebar = 2131034190;
			
			// aapt resource value: 0x7f05005e
			public const int roomname = 2131034206;
			
			// aapt resource value: 0x7f050052
			public const int roomsrefreshbutton = 2131034194;
			
			// aapt resource value: 0x7f050051
			public const int roomsrefreshbuttoncontainer = 2131034193;
			
			// aapt resource value: 0x7f050053
			public const int roomsrefreshthrobber = 2131034195;
			
			// aapt resource value: 0x7f05001e
			public const int rootview = 2131034142;
			
			// aapt resource value: 0x7f05005f
			public const int rotarybackground = 2131034207;
			
			// aapt resource value: 0x7f050061
			public const int rotarycentrebutton = 2131034209;
			
			// aapt resource value: 0x7f050060
			public const int rotarygrip = 2131034208;
			
			// aapt resource value: 0x7f05004a
			public const int selectroombutton = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int selectsourcebutton = 2131034187;
			
			// aapt resource value: 0x7f050001
			public const int settingsbutton = 2131034113;
			
			// aapt resource value: 0x7f05003d
			public const int shufflebutton = 2131034173;
			
			// aapt resource value: 0x7f050065
			public const int sourceicon = 2131034213;
			
			// aapt resource value: 0x7f05005a
			public const int sourcelist = 2131034202;
			
			// aapt resource value: 0x7f050057
			public const int sourcelistbackbutton = 2131034199;
			
			// aapt resource value: 0x7f050055
			public const int sourcelistcontainer = 2131034197;
			
			// aapt resource value: 0x7f050058
			public const int sourcelisttitle = 2131034200;
			
			// aapt resource value: 0x7f050056
			public const int sourcelisttitlebar = 2131034198;
			
			// aapt resource value: 0x7f050067
			public const int sourcename = 2131034215;
			
			// aapt resource value: 0x7f050063
			public const int sourcesrefreshbutton = 2131034211;
			
			// aapt resource value: 0x7f050062
			public const int sourcesrefreshbuttoncontainer = 2131034210;
			
			// aapt resource value: 0x7f050064
			public const int sourcesrefreshthrobber = 2131034212;
			
			// aapt resource value: 0x7f050059
			public const int sourcesstandbybutton = 2131034201;
			
			// aapt resource value: 0x7f05005c
			public const int standbybutton = 2131034204;
			
			// aapt resource value: 0x7f05004f
			public const int standbybuttonall = 2131034191;
			
			// aapt resource value: 0x7f050075
			public const int timedisplay = 2131034229;
			
			// aapt resource value: 0x7f05002b
			public const int topbar = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int topcontainer = 2131034154;
			
			// aapt resource value: 0x7f050068
			public const int trackartwork = 2131034216;
			
			// aapt resource value: 0x7f050072
			public const int trackartworkcontainer = 2131034226;
			
			// aapt resource value: 0x7f050028
			public const int trackartworkfullscreen = 2131034152;
			
			// aapt resource value: 0x7f050023
			public const int trackcontrols = 2131034147;
			
			// aapt resource value: 0x7f05002e
			public const int trackcontrolsfullscreen = 2131034158;
			
			// aapt resource value: 0x7f05006a
			public const int trackdisplay1 = 2131034218;
			
			// aapt resource value: 0x7f05006e
			public const int trackdisplay1fullscreen = 2131034222;
			
			// aapt resource value: 0x7f05006b
			public const int trackdisplay2 = 2131034219;
			
			// aapt resource value: 0x7f05006f
			public const int trackdisplay2fullscreen = 2131034223;
			
			// aapt resource value: 0x7f05006c
			public const int trackdisplay3 = 2131034220;
			
			// aapt resource value: 0x7f050070
			public const int trackdisplay3fullscreen = 2131034224;
			
			// aapt resource value: 0x7f050069
			public const int trackdisplaycontainer = 2131034217;
			
			// aapt resource value: 0x7f050073
			public const int trackshowplaylistbutton = 2131034227;
			
			// aapt resource value: 0x7f05006d
			public const int tracktechnicalinfo = 2131034221;
			
			// aapt resource value: 0x7f050071
			public const int tracktechnicalinfofullscreen = 2131034225;
			
			// aapt resource value: 0x7f050074
			public const int transportcontrols = 2131034228;
			
			// aapt resource value: 0x7f05001f
			public const int viewpageindicatorphone = 2131034143;
			
			// aapt resource value: 0x7f050035
			public const int viewpagerphone = 2131034165;
			
			// aapt resource value: 0x7f050049
			public const int viewsourceselection = 2131034185;
			
			// aapt resource value: 0x7f050021
			public const int volumeandtransportcontrols = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int volumeandtransportcontrolscontainer = 2131034144;
			
			// aapt resource value: 0x7f050076
			public const int volumedisplay = 2131034230;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BackButton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BrowserButtons = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BrowserControls = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BrowserErrorPanel = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BrowserItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BrowserMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BrowserScreenPhone = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ButtonControl = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CancelButton = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ConfirmDeleteButton = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int DummyPhone = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int DummyTablet = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int EditButton = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int HelpAbout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MainPhone = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MainTablet = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int MoveDownButton = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int MoveUpButton = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PlaylistButtons = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PlaylistButtonsPhone = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int PlaylistItem = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int PlaylistScreenPhone = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int RequestDeleteButton = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int RoomAndSourceControls = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int RoomAndSourceControlsPhone = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int RoomList = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int RoomListItem = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int RotaryControl = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int SaveButton = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SourceList = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int SourceListItem = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int TrackControls = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int TrackControlsFullscreen = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int TrackControlsPhone = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int VolumeAndTransportControls = 2130903074;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040006
			public const int dividerbackground = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hugetextview = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int largetextview = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int mediumtextview = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int semilargetextview = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int smalltextview = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int splitterleft = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int splitterright = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int textviewtext = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int tinytextview = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int toolbardimensions = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int topcontainerdimensions = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int trackartworkcontainerdimensions = 2130968581;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
