#!/bin/sh

UPDATE=$(osascript <<EOD
  try
    return (version of application "Songcast") starts with "4.4."
  on error
  	return false
  end try
EOD)

if ! $UPDATE ; then exit 0 ; fi

CURRUSER=`logname`
SONGCAST_URI="http://oss.linn.co.uk/Releases/Songcast/Davaar/songcast_latest_osx.dmg"
DMG_FILE="/Users/$CURRUSER/Downloads/songcast_latest_osx.dmg"
MOUNT_POINT="/Volumes/LinnSongcast"
PKG_FILE=$MOUNT_POINT/Installer.pkg

# download songcast dmg file
rm -f $DMG_FILE
curl $SONGCAST_URI > $DMG_FILE

# mount the dmg file
hdiutil detach -quiet $MOUNT_POINT
hdiutil attach $DMG_FILE -mountpoint $MOUNT_POINT

# run the installer
installer -pkg $PKG_FILE -target /

# unmount the dmg and remove the downloaded file
hdiutil detach -quiet $MOUNT_POINT
rm -f $DMG_FILE

# restart songcast for the current user
su -l $CURRUSER -c 'launchctl load /Library/LaunchAgents/uk.co.linn.songcast.plist'