using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.ComponentModel;
using Linn.Kinsky;
using Linn.ControlPoint.Upnp;
using Linn.Control.Ssdp;
using System.Net;
using Linn;
using System.Collections.ObjectModel;
using System.IO;
using System.Threading;

namespace KinskyDesktopWpf
{

    public partial class CrashLogDialog : Window
    {
        public CrashLogDialog(string aTitle, string aReportText, string aProduct, string aVersion)
        {
            InitializeComponent();
            iProduct = aProduct;
            iVersion = aVersion;
            this.Title = aTitle;
            txtMessage.Text = aTitle + " has encountered a problem and needs to close. We are sorry for the inconvenience";
            txtMessage2.Text = "We have created an error report that you can send to help us improve " + aTitle;
            txtErrorDetails.Text = aReportText;
            btnSendReport.Focus();
        }


        #region Command Bindings

        private void CloseCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
            e.Handled = true;
        }

        private void CloseExecuted(object sender, ExecutedRoutedEventArgs e)
        {
            Close();
        }
        #endregion

        protected override void OnClosed(EventArgs e)
        {
            EventHandler<EventArgs> eventClosed = EventDialogClosed;
            if (eventClosed != null)
            {
                eventClosed(this, EventArgs.Empty);
            }
            base.OnClosed(e);
        }

        private void btnSendReport_Click(object sender, RoutedEventArgs e)
        {
            // post data to Linn
            try
            {
                DebugReport report = new DebugReport("Crash log generated by " + iProduct + " ver " + iVersion);
                report.Post(Title, txtErrorDetails.Text);
            }
            catch { } //failed to send debug report, nothing we can do...
            Close();
        }

        private void btnToggleDetails_Click(object sender, RoutedEventArgs e)
        {
            if (txtErrorDetails.Visibility == Visibility.Collapsed)
            {
                txtErrorDetails.Visibility = Visibility.Visible;
                Height = 514;
            }
            else
            {
                txtErrorDetails.Visibility = Visibility.Collapsed;
                Height = 238;
            }
        }
        private string iProduct;
        private string iVersion;
        public event EventHandler<EventArgs> EventDialogClosed;

    }
}
