// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinskyTouch {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("CellLazyLoadDefaultFactory")]
	public partial class CellLazyLoadDefaultFactory {
		
		private CellLazyLoadDefault __mt_cellLazyLoadDefault;
		
		#pragma warning disable 0169
		[Foundation.Connect("cellLazyLoadDefault")]
		private CellLazyLoadDefault cellLazyLoadDefault {
			get {
				this.__mt_cellLazyLoadDefault = ((CellLazyLoadDefault)(this.GetNativeField("cellLazyLoadDefault")));
				return this.__mt_cellLazyLoadDefault;
			}
			set {
				this.__mt_cellLazyLoadDefault = value;
				this.SetNativeField("cellLazyLoadDefault", value);
			}
		}
	}
	
	// Base type probably should be UIKit.UITableViewCell or subclass
	[Foundation.Register("CellLazyLoadDefault")]
	public partial class CellLazyLoadDefault {
		
		private UIKit.UIImageView __mt_imageViewArtwork;
		
		private UIKit.UILabel __mt_labelTitle;
		
		#pragma warning disable 0169
		[Foundation.Connect("imageViewArtwork")]
		private UIKit.UIImageView imageViewArtwork {
			get {
				this.__mt_imageViewArtwork = ((UIKit.UIImageView)(this.GetNativeField("imageViewArtwork")));
				return this.__mt_imageViewArtwork;
			}
			set {
				this.__mt_imageViewArtwork = value;
				this.SetNativeField("imageViewArtwork", value);
			}
		}
		
		[Foundation.Connect("labelTitle")]
		private UIKit.UILabel labelTitle {
			get {
				this.__mt_labelTitle = ((UIKit.UILabel)(this.GetNativeField("labelTitle")));
				return this.__mt_labelTitle;
			}
			set {
				this.__mt_labelTitle = value;
				this.SetNativeField("labelTitle", value);
			}
		}
	}	
}
